version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: datascientest
      MONGO_INITDB_ROOT_PASSWORD: dst123
    volumes:
      - mongodb-data:/data/db
    networks:
      - mlnet


  fastapi_app:
    build:
      context: .
    container_name: rakuten-app
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
      - "5001:5001"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=datascientest
      - MONGO_PASSWORD=dst123
    networks:
      - mlnet

volumes:
  mongodb-data:

networks:
  mlnet: